// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Read$Rackette = require("./Read.bs.js");
var CS17SetupRackette$Rackette = require("./CS17SetupRackette.bs.js");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(+ 4 5)"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "+"
          },
          tl: {
            hd: {
              TAG: /* NumberC */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* NumberC */0,
                _0: 5
              },
              tl: /* [] */0
            }
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 1");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(+ 4 (* 16 932))"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "+"
          },
          tl: {
            hd: {
              TAG: /* NumberC */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* SymbolC */1,
                    _0: "*"
                  },
                  tl: {
                    hd: {
                      TAG: /* NumberC */0,
                      _0: 16
                    },
                    tl: {
                      hd: {
                        TAG: /* NumberC */0,
                        _0: 932
                      },
                      tl: /* [] */0
                    }
                  }
                }
              },
              tl: /* [] */0
            }
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 2");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(first (cons 3 (cons 2 empty)))"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "first"
          },
          tl: {
            hd: {
              TAG: /* ListC */2,
              _0: {
                hd: {
                  TAG: /* SymbolC */1,
                  _0: "cons"
                },
                tl: {
                  hd: {
                    TAG: /* NumberC */0,
                    _0: 3
                  },
                  tl: {
                    hd: {
                      TAG: /* ListC */2,
                      _0: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "cons"
                        },
                        tl: {
                          hd: {
                            TAG: /* NumberC */0,
                            _0: 2
                          },
                          tl: {
                            hd: {
                              TAG: /* SymbolC */1,
                              _0: "empty"
                            },
                            tl: /* [] */0
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            },
            tl: /* [] */0
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 3");

/*  Not a pure module */
