// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Read$Rackette = require("./Read.bs.js");
var Rackette$Rackette = require("./Rackette.bs.js");
var CS17SetupRackette$Rackette = require("./CS17SetupRackette.bs.js");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(+ 4 5)"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "+"
          },
          tl: {
            hd: {
              TAG: /* NumberC */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* NumberC */0,
                _0: 5
              },
              tl: /* [] */0
            }
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 1");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(+ 4 (* 16 932))"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "+"
          },
          tl: {
            hd: {
              TAG: /* NumberC */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* SymbolC */1,
                    _0: "*"
                  },
                  tl: {
                    hd: {
                      TAG: /* NumberC */0,
                      _0: 16
                    },
                    tl: {
                      hd: {
                        TAG: /* NumberC */0,
                        _0: 932
                      },
                      tl: /* [] */0
                    }
                  }
                }
              },
              tl: /* [] */0
            }
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 2");

CS17SetupRackette$Rackette.checkExpectConcreteProgram(Read$Rackette.Reader.readAll("(first (cons 3 (cons 2 empty)))"), {
      hd: {
        TAG: /* ListC */2,
        _0: {
          hd: {
            TAG: /* SymbolC */1,
            _0: "first"
          },
          tl: {
            hd: {
              TAG: /* ListC */2,
              _0: {
                hd: {
                  TAG: /* SymbolC */1,
                  _0: "cons"
                },
                tl: {
                  hd: {
                    TAG: /* NumberC */0,
                    _0: 3
                  },
                  tl: {
                    hd: {
                      TAG: /* ListC */2,
                      _0: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "cons"
                        },
                        tl: {
                          hd: {
                            TAG: /* NumberC */0,
                            _0: 2
                          },
                          tl: {
                            hd: {
                              TAG: /* SymbolC */1,
                              _0: "empty"
                            },
                            tl: /* [] */0
                          }
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              }
            },
            tl: /* [] */0
          }
        }
      },
      tl: /* [] */0
    }, "readAll test - 3");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.lambdaNamesToName({
          hd: {
            TAG: /* SymbolC */1,
            _0: "+"
          },
          tl: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "x"
            },
            tl: /* [] */0
          }
        }), {
      hd: /* Name */{
        _0: "+"
      },
      tl: {
        hd: /* Name */{
          _0: "x"
        },
        tl: /* [] */0
      }
    }, "lambdaNamesToName - 1");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* NumberC */0,
          _0: 4
        }), {
      TAG: /* NumE */0,
      _0: 4
    }, "parseExpression - single num");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* SymbolC */1,
          _0: "true"
        }), {
      TAG: /* BoolE */1,
      _0: true
    }, "parseExpression - true");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* SymbolC */1,
          _0: "false"
        }), {
      TAG: /* BoolE */1,
      _0: false
    }, "parseExpression - false");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* SymbolC */1,
          _0: "empty"
        }), /* EmptyE */0, "parseExpression - empty");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* SymbolC */1,
          _0: "x"
        }), {
      TAG: /* NameE */2,
      _0: /* Name */{
        _0: "x"
      }
    }, "parseExpression - some variable");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "and"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "true"
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "="
                    },
                    tl: {
                      hd: {
                        TAG: /* NumberC */0,
                        _0: 4
                      },
                      tl: {
                        hd: {
                          TAG: /* NumberC */0,
                          _0: 4
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* AndE */3,
      _0: {
        TAG: /* BoolE */1,
        _0: true
      },
      _1: {
        TAG: /* ApplicationE */9,
        _0: {
          hd: {
            TAG: /* NameE */2,
            _0: /* Name */{
              _0: "="
            }
          },
          tl: {
            hd: {
              TAG: /* NumE */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* NumE */0,
                _0: 4
              },
              tl: /* [] */0
            }
          }
        }
      }
    }, "parseExpression - and statement");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "or"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "true"
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "="
                    },
                    tl: {
                      hd: {
                        TAG: /* NumberC */0,
                        _0: 4
                      },
                      tl: {
                        hd: {
                          TAG: /* NumberC */0,
                          _0: 4
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* OrE */4,
      _0: {
        TAG: /* BoolE */1,
        _0: true
      },
      _1: {
        TAG: /* ApplicationE */9,
        _0: {
          hd: {
            TAG: /* NameE */2,
            _0: /* Name */{
              _0: "="
            }
          },
          tl: {
            hd: {
              TAG: /* NumE */0,
              _0: 4
            },
            tl: {
              hd: {
                TAG: /* NumE */0,
                _0: 4
              },
              tl: /* [] */0
            }
          }
        }
      }
    }, "parseExpression - or statement");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "if"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "true"
              },
              tl: {
                hd: {
                  TAG: /* NumberC */0,
                  _0: 7
                },
                tl: {
                  hd: {
                    TAG: /* ListC */2,
                    _0: {
                      hd: {
                        TAG: /* SymbolC */1,
                        _0: "+"
                      },
                      tl: {
                        hd: {
                          TAG: /* NumberC */0,
                          _0: 4
                        },
                        tl: {
                          hd: {
                            TAG: /* NumberC */0,
                            _0: 18
                          },
                          tl: /* [] */0
                        }
                      }
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          }
        }), {
      TAG: /* IfE */5,
      _0: {
        boolExpr: {
          TAG: /* BoolE */1,
          _0: true
        },
        trueExpr: {
          TAG: /* NumE */0,
          _0: 7
        },
        falseExpr: {
          TAG: /* ApplicationE */9,
          _0: {
            hd: {
              TAG: /* NameE */2,
              _0: /* Name */{
                _0: "+"
              }
            },
            tl: {
              hd: {
                TAG: /* NumE */0,
                _0: 4
              },
              tl: {
                hd: {
                  TAG: /* NumE */0,
                  _0: 18
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, "parseExpression - if statement");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "cond"
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* SymbolC */1,
                    _0: "true"
                  },
                  tl: {
                    hd: {
                      TAG: /* NumberC */0,
                      _0: 1
                    },
                    tl: /* [] */0
                  }
                }
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* ListC */2,
                      _0: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "="
                        },
                        tl: {
                          hd: {
                            TAG: /* NumberC */0,
                            _0: 4
                          },
                          tl: {
                            hd: {
                              TAG: /* NumberC */0,
                              _0: 4
                            },
                            tl: /* [] */0
                          }
                        }
                      }
                    },
                    tl: {
                      hd: {
                        TAG: /* NumberC */0,
                        _0: 2
                      },
                      tl: /* [] */0
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* CondE */6,
      _0: {
        hd: {
          conditionExpr: {
            TAG: /* BoolE */1,
            _0: true
          },
          resultExpr: {
            TAG: /* NumE */0,
            _0: 1
          }
        },
        tl: {
          hd: {
            conditionExpr: {
              TAG: /* ApplicationE */9,
              _0: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "="
                  }
                },
                tl: {
                  hd: {
                    TAG: /* NumE */0,
                    _0: 4
                  },
                  tl: {
                    hd: {
                      TAG: /* NumE */0,
                      _0: 4
                    },
                    tl: /* [] */0
                  }
                }
              }
            },
            resultExpr: {
              TAG: /* NumE */0,
              _0: 2
            }
          },
          tl: /* [] */0
        }
      }
    }, "parseExpression - cond statement");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "lambda"
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* SymbolC */1,
                    _0: "x"
                  },
                  tl: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "y"
                    },
                    tl: /* [] */0
                  }
                }
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "+"
                    },
                    tl: {
                      hd: {
                        TAG: /* SymbolC */1,
                        _0: "x"
                      },
                      tl: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "y"
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* LambdaE */7,
      _0: {
        nameList: {
          hd: /* Name */{
            _0: "x"
          },
          tl: {
            hd: /* Name */{
              _0: "y"
            },
            tl: /* [] */0
          }
        },
        lambdaBody: {
          TAG: /* ApplicationE */9,
          _0: {
            hd: {
              TAG: /* NameE */2,
              _0: /* Name */{
                _0: "+"
              }
            },
            tl: {
              hd: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "x"
                }
              },
              tl: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "y"
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, "parseExpression - lambda statement");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "let"
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* ListC */2,
                    _0: {
                      hd: {
                        TAG: /* SymbolC */1,
                        _0: "x"
                      },
                      tl: {
                        hd: {
                          TAG: /* NumberC */0,
                          _0: 5
                        },
                        tl: /* [] */0
                      }
                    }
                  },
                  tl: {
                    hd: {
                      TAG: /* ListC */2,
                      _0: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "y"
                        },
                        tl: {
                          hd: {
                            TAG: /* NumberC */0,
                            _0: 4
                          },
                          tl: /* [] */0
                        }
                      }
                    },
                    tl: /* [] */0
                  }
                }
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "-"
                    },
                    tl: {
                      hd: {
                        TAG: /* SymbolC */1,
                        _0: "x"
                      },
                      tl: {
                        hd: {
                          TAG: /* SymbolC */1,
                          _0: "y"
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* LetE */8,
      _0: {
        letPairs: {
          hd: {
            pairName: /* Name */{
              _0: "x"
            },
            pairExpr: {
              TAG: /* NumE */0,
              _0: 5
            }
          },
          tl: {
            hd: {
              pairName: /* Name */{
                _0: "y"
              },
              pairExpr: {
                TAG: /* NumE */0,
                _0: 4
              }
            },
            tl: /* [] */0
          }
        },
        letBody: {
          TAG: /* ApplicationE */9,
          _0: {
            hd: {
              TAG: /* NameE */2,
              _0: /* Name */{
                _0: "-"
              }
            },
            tl: {
              hd: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "x"
                }
              },
              tl: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "y"
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, "parseExpression - let statement");

CS17SetupRackette$Rackette.checkExpectDefinition(Rackette$Rackette.parseDefinition({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "define"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "x"
              },
              tl: {
                hd: {
                  TAG: /* NumberC */0,
                  _0: 5
                },
                tl: /* [] */0
              }
            }
          }
        }), [
      /* Name */{
        _0: "x"
      },
      {
        TAG: /* NumE */0,
        _0: 5
      }
    ], "parseDefinition  - var to number");

CS17SetupRackette$Rackette.checkExpectDefinition(Rackette$Rackette.parseDefinition({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "define"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "addOne"
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "lambda"
                    },
                    tl: {
                      hd: {
                        TAG: /* ListC */2,
                        _0: {
                          hd: {
                            TAG: /* SymbolC */1,
                            _0: "x"
                          },
                          tl: /* [] */0
                        }
                      },
                      tl: {
                        hd: {
                          TAG: /* ListC */2,
                          _0: {
                            hd: {
                              TAG: /* SymbolC */1,
                              _0: "+"
                            },
                            tl: {
                              hd: {
                                TAG: /* SymbolC */1,
                                _0: "x"
                              },
                              tl: {
                                hd: {
                                  TAG: /* NumberC */0,
                                  _0: 1
                                },
                                tl: /* [] */0
                              }
                            }
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), [
      /* Name */{
        _0: "addOne"
      },
      {
        TAG: /* LambdaE */7,
        _0: {
          nameList: {
            hd: /* Name */{
              _0: "x"
            },
            tl: /* [] */0
          },
          lambdaBody: {
            TAG: /* ApplicationE */9,
            _0: {
              hd: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "+"
                }
              },
              tl: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "x"
                  }
                },
                tl: {
                  hd: {
                    TAG: /* NumE */0,
                    _0: 1
                  },
                  tl: /* [] */0
                }
              }
            }
          }
        }
      }
    ], "parseDefinition - function with lambda");

CS17SetupRackette$Rackette.checkExpectAbstractProgramPiece(Rackette$Rackette.parsePiece({
          TAG: /* NumberC */0,
          _0: 1
        }), {
      TAG: /* Expression */1,
      _0: {
        TAG: /* NumE */0,
        _0: 1
      }
    }, "parsePiece - single number");

CS17SetupRackette$Rackette.checkExpectAbstractProgramPiece(Rackette$Rackette.parsePiece({
          TAG: /* SymbolC */1,
          _0: "empty"
        }), {
      TAG: /* Expression */1,
      _0: /* EmptyE */0
    }, "parsePiece - empty");

CS17SetupRackette$Rackette.checkExpectAbstractProgramPiece(Rackette$Rackette.parsePiece({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "+"
            },
            tl: {
              hd: {
                TAG: /* NumberC */0,
                _0: 2
              },
              tl: {
                hd: {
                  TAG: /* NumberC */0,
                  _0: 5
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* Expression */1,
      _0: {
        TAG: /* ApplicationE */9,
        _0: {
          hd: {
            TAG: /* NameE */2,
            _0: /* Name */{
              _0: "+"
            }
          },
          tl: {
            hd: {
              TAG: /* NumE */0,
              _0: 2
            },
            tl: {
              hd: {
                TAG: /* NumE */0,
                _0: 5
              },
              tl: /* [] */0
            }
          }
        }
      }
    }, "parsePiece - procedure application expression");

CS17SetupRackette$Rackette.checkExpectAbstractProgramPiece(Rackette$Rackette.parsePiece({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "define"
            },
            tl: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "x"
              },
              tl: {
                hd: {
                  TAG: /* NumberC */0,
                  _0: 5
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* Definition */0,
      _0: [
        /* Name */{
          _0: "x"
        },
        {
          TAG: /* NumE */0,
          _0: 5
        }
      ]
    }, "parsePiece - definition");

CS17SetupRackette$Rackette.checkExpectAbstractProgram(Rackette$Rackette.parse({
          hd: {
            TAG: /* NumberC */0,
            _0: 5
          },
          tl: {
            hd: {
              TAG: /* NumberC */0,
              _0: 4
            },
            tl: /* [] */0
          }
        }), {
      hd: {
        TAG: /* Expression */1,
        _0: {
          TAG: /* NumE */0,
          _0: 5
        }
      },
      tl: {
        hd: {
          TAG: /* Expression */1,
          _0: {
            TAG: /* NumE */0,
            _0: 4
          }
        },
        tl: /* [] */0
      }
    }, "parse - two nums");

CS17SetupRackette$Rackette.checkExpectAbstractProgram(Rackette$Rackette.parse({
          hd: {
            TAG: /* ListC */2,
            _0: {
              hd: {
                TAG: /* SymbolC */1,
                _0: "define"
              },
              tl: {
                hd: {
                  TAG: /* SymbolC */1,
                  _0: "x"
                },
                tl: {
                  hd: {
                    TAG: /* NumberC */0,
                    _0: 5
                  },
                  tl: /* [] */0
                }
              }
            }
          },
          tl: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "x"
            },
            tl: /* [] */0
          }
        }), {
      hd: {
        TAG: /* Definition */0,
        _0: [
          /* Name */{
            _0: "x"
          },
          {
            TAG: /* NumE */0,
            _0: 5
          }
        ]
      },
      tl: {
        hd: {
          TAG: /* Expression */1,
          _0: {
            TAG: /* NameE */2,
            _0: /* Name */{
              _0: "x"
            }
          }
        },
        tl: /* [] */0
      }
    }, "parse - definition and variable call");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* NumE */0,
              _0: 5
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 5
      },
      tl: /* [] */0
    }, "process - single number");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* ApplicationE */9,
              _0: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "+"
                  }
                },
                tl: {
                  hd: {
                    TAG: /* NumE */0,
                    _0: 5
                  },
                  tl: {
                    hd: {
                      TAG: /* NumE */0,
                      _0: 12
                    },
                    tl: /* [] */0
                  }
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 17
      },
      tl: /* [] */0
    }, "process - addition builtin");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Definition */0,
            _0: [
              /* Name */{
                _0: "addOne"
              },
              {
                TAG: /* LambdaE */7,
                _0: {
                  nameList: {
                    hd: /* Name */{
                      _0: "x"
                    },
                    tl: /* [] */0
                  },
                  lambdaBody: {
                    TAG: /* ApplicationE */9,
                    _0: {
                      hd: {
                        TAG: /* NameE */2,
                        _0: /* Name */{
                          _0: "+"
                        }
                      },
                      tl: {
                        hd: {
                          TAG: /* NameE */2,
                          _0: /* Name */{
                            _0: "x"
                          }
                        },
                        tl: {
                          hd: {
                            TAG: /* NumE */0,
                            _0: 1
                          },
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                }
              }
            ]
          },
          tl: {
            hd: {
              TAG: /* Expression */1,
              _0: {
                TAG: /* ApplicationE */9,
                _0: {
                  hd: {
                    TAG: /* NameE */2,
                    _0: /* Name */{
                      _0: "addOne"
                    }
                  },
                  tl: {
                    hd: {
                      TAG: /* NumE */0,
                      _0: 5
                    },
                    tl: /* [] */0
                  }
                }
              }
            },
            tl: /* [] */0
          }
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 6
      },
      tl: /* [] */0
    }, "process - user defined expression definition and application");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Definition */0,
            _0: [
              /* Name */{
                _0: "x"
              },
              {
                TAG: /* NumE */0,
                _0: 23
              }
            ]
          },
          tl: {
            hd: {
              TAG: /* Expression */1,
              _0: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "x"
                }
              }
            },
            tl: /* [] */0
          }
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 23
      },
      tl: /* [] */0
    }, "process - variable definition and use");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* BoolE */1,
              _0: true
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: true
      },
      tl: /* [] */0
    }, "process - true");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* BoolE */1,
              _0: false
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: false
      },
      tl: /* [] */0
    }, "process - false");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: /* EmptyE */0
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* ListV */2,
        _0: /* [] */0
      },
      tl: /* [] */0
    }, "process - empty");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* AndE */3,
              _0: {
                TAG: /* BoolE */1,
                _0: true
              },
              _1: {
                TAG: /* BoolE */1,
                _0: true
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: true
      },
      tl: /* [] */0
    }, "process - and with two trues");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* AndE */3,
              _0: {
                TAG: /* BoolE */1,
                _0: true
              },
              _1: {
                TAG: /* BoolE */1,
                _0: false
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: false
      },
      tl: /* [] */0
    }, "process - and with one true - 1");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* AndE */3,
              _0: {
                TAG: /* BoolE */1,
                _0: false
              },
              _1: {
                TAG: /* BoolE */1,
                _0: true
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: false
      },
      tl: /* [] */0
    }, "process - and with one true - 2");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* AndE */3,
              _0: {
                TAG: /* BoolE */1,
                _0: false
              },
              _1: {
                TAG: /* BoolE */1,
                _0: false
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: false
      },
      tl: /* [] */0
    }, "process - and with two falses");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* OrE */4,
              _0: {
                TAG: /* BoolE */1,
                _0: true
              },
              _1: {
                TAG: /* BoolE */1,
                _0: true
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: true
      },
      tl: /* [] */0
    }, "process - or with two trues");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* OrE */4,
              _0: {
                TAG: /* BoolE */1,
                _0: true
              },
              _1: {
                TAG: /* BoolE */1,
                _0: false
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: true
      },
      tl: /* [] */0
    }, "process - or with one true - 1");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* OrE */4,
              _0: {
                TAG: /* BoolE */1,
                _0: false
              },
              _1: {
                TAG: /* BoolE */1,
                _0: true
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: true
      },
      tl: /* [] */0
    }, "process - or with one true - 2");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* OrE */4,
              _0: {
                TAG: /* BoolE */1,
                _0: false
              },
              _1: {
                TAG: /* BoolE */1,
                _0: false
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* BoolV */1,
        _0: false
      },
      tl: /* [] */0
    }, "process - or with two falses");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* IfE */5,
              _0: {
                boolExpr: {
                  TAG: /* BoolE */1,
                  _0: true
                },
                trueExpr: {
                  TAG: /* NumE */0,
                  _0: 1
                },
                falseExpr: {
                  TAG: /* NumE */0,
                  _0: -1
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 1
      },
      tl: /* [] */0
    }, "process - if with true");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* IfE */5,
              _0: {
                boolExpr: {
                  TAG: /* BoolE */1,
                  _0: false
                },
                trueExpr: {
                  TAG: /* NumE */0,
                  _0: 1
                },
                falseExpr: {
                  TAG: /* NumE */0,
                  _0: -1
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: -1
      },
      tl: /* [] */0
    }, "process - if with false");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* CondE */6,
              _0: {
                hd: {
                  conditionExpr: {
                    TAG: /* BoolE */1,
                    _0: false
                  },
                  resultExpr: {
                    TAG: /* NumE */0,
                    _0: 0
                  }
                },
                tl: {
                  hd: {
                    conditionExpr: {
                      TAG: /* BoolE */1,
                      _0: true
                    },
                    resultExpr: {
                      TAG: /* NumE */0,
                      _0: 1
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 1
      },
      tl: /* [] */0
    }, "prcoess - cond 1");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* CondE */6,
              _0: {
                hd: {
                  conditionExpr: {
                    TAG: /* BoolE */1,
                    _0: true
                  },
                  resultExpr: {
                    TAG: /* NumE */0,
                    _0: 0
                  }
                },
                tl: {
                  hd: {
                    conditionExpr: {
                      TAG: /* BoolE */1,
                      _0: true
                    },
                    resultExpr: {
                      TAG: /* NumE */0,
                      _0: 1
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 0
      },
      tl: /* [] */0
    }, "prcoess - cond 2");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* LambdaE */7,
              _0: {
                nameList: {
                  hd: /* Name */{
                    _0: "x"
                  },
                  tl: {
                    hd: /* Name */{
                      _0: "y"
                    },
                    tl: /* [] */0
                  }
                },
                lambdaBody: {
                  TAG: /* ApplicationE */9,
                  _0: {
                    hd: {
                      TAG: /* NameE */2,
                      _0: /* Name */{
                        _0: "-"
                      }
                    },
                    tl: {
                      hd: {
                        TAG: /* NameE */2,
                        _0: /* Name */{
                          _0: "x"
                        }
                      },
                      tl: {
                        hd: {
                          TAG: /* NameE */2,
                          _0: /* Name */{
                            _0: "y"
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* ClosureV */4,
        _0: {
          cNameList: {
            hd: /* Name */{
              _0: "x"
            },
            tl: {
              hd: /* Name */{
                _0: "y"
              },
              tl: /* [] */0
            }
          },
          cExpr: {
            TAG: /* ApplicationE */9,
            _0: {
              hd: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "-"
                }
              },
              tl: {
                hd: {
                  TAG: /* NameE */2,
                  _0: /* Name */{
                    _0: "x"
                  }
                },
                tl: {
                  hd: {
                    TAG: /* NameE */2,
                    _0: /* Name */{
                      _0: "y"
                    }
                  },
                  tl: /* [] */0
                }
              }
            }
          },
          cEnv: /* [] */0
        }
      },
      tl: /* [] */0
    }, "process - lambda");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.$$process({
          hd: {
            TAG: /* Expression */1,
            _0: {
              TAG: /* LetE */8,
              _0: {
                letPairs: {
                  hd: {
                    pairName: /* Name */{
                      _0: "x"
                    },
                    pairExpr: {
                      TAG: /* NumE */0,
                      _0: 10
                    }
                  },
                  tl: {
                    hd: {
                      pairName: /* Name */{
                        _0: "y"
                      },
                      pairExpr: {
                        TAG: /* NumE */0,
                        _0: 2
                      }
                    },
                    tl: /* [] */0
                  }
                },
                letBody: {
                  TAG: /* ApplicationE */9,
                  _0: {
                    hd: {
                      TAG: /* NameE */2,
                      _0: /* Name */{
                        _0: "*"
                      }
                    },
                    tl: {
                      hd: {
                        TAG: /* NameE */2,
                        _0: /* Name */{
                          _0: "x"
                        }
                      },
                      tl: {
                        hd: {
                          TAG: /* NameE */2,
                          _0: /* Name */{
                            _0: "y"
                          }
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            }
          },
          tl: /* [] */0
        }), {
      hd: {
        TAG: /* NumV */0,
        _0: 20
      },
      tl: /* [] */0
    }, "process - let");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* NumV */0,
          _0: 4
        }), "4", "stringOfValue - single number");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* BoolV */1,
          _0: true
        }), "#t", "stringOfValue - true");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* BoolV */1,
          _0: false
        }), "#f", "stringOfValue - false");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* ListV */2,
          _0: {
            hd: {
              TAG: /* NumV */0,
              _0: 1
            },
            tl: {
              hd: {
                TAG: /* NumV */0,
                _0: 2
              },
              tl: {
                hd: {
                  TAG: /* NumV */0,
                  _0: 3
                },
                tl: /* [] */0
              }
            }
          }
        }), "[1,2,3]", "stringOfValue - list");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* ListV */2,
          _0: /* [] */0
        }), "empty", "stringOfValue - empty list");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.stringOfValue({
          TAG: /* BuiltinV */3,
          _0: {
            printedRep: "myPrint",
            bProc: (function (_thisIsAPlaceholder) {
                return {
                        TAG: /* BoolV */1,
                        _0: true
                      };
              })
          }
        }), "myPrint", "StringOfValue - builtIn");

CS17SetupRackette$Rackette.checkExpectConcreteProgramPiece(Read$Rackette.Reader.read("(addOne 5)"), {
      TAG: /* ListC */2,
      _0: {
        hd: {
          TAG: /* SymbolC */1,
          _0: "addOne"
        },
        tl: {
          hd: {
            TAG: /* NumberC */0,
            _0: 5
          },
          tl: /* [] */0
        }
      }
    }, "read - procedure application expression");

CS17SetupRackette$Rackette.checkExpectExpression(Rackette$Rackette.parseExpression({
          TAG: /* ListC */2,
          _0: {
            hd: {
              TAG: /* SymbolC */1,
              _0: "lambda"
            },
            tl: {
              hd: {
                TAG: /* ListC */2,
                _0: {
                  hd: {
                    TAG: /* SymbolC */1,
                    _0: "x"
                  },
                  tl: /* [] */0
                }
              },
              tl: {
                hd: {
                  TAG: /* ListC */2,
                  _0: {
                    hd: {
                      TAG: /* SymbolC */1,
                      _0: "+"
                    },
                    tl: {
                      hd: {
                        TAG: /* SymbolC */1,
                        _0: "x"
                      },
                      tl: {
                        hd: {
                          TAG: /* NumberC */0,
                          _0: 1
                        },
                        tl: /* [] */0
                      }
                    }
                  }
                },
                tl: /* [] */0
              }
            }
          }
        }), {
      TAG: /* LambdaE */7,
      _0: {
        nameList: {
          hd: /* Name */{
            _0: "x"
          },
          tl: /* [] */0
        },
        lambdaBody: {
          TAG: /* ApplicationE */9,
          _0: {
            hd: {
              TAG: /* NameE */2,
              _0: /* Name */{
                _0: "+"
              }
            },
            tl: {
              hd: {
                TAG: /* NameE */2,
                _0: /* Name */{
                  _0: "x"
                }
              },
              tl: {
                hd: {
                  TAG: /* NumE */0,
                  _0: 1
                },
                tl: /* [] */0
              }
            }
          }
        }
      }
    }, "lambda again");

CS17SetupRackette$Rackette.checkExpectDefinition(Rackette$Rackette.parseDefinition(Read$Rackette.Reader.read("(define addOne (lambda (x) (+ x 1)))")), [
      /* Name */{
        _0: "addOne"
      },
      Rackette$Rackette.parseExpression(Read$Rackette.Reader.read("(lambda (x) (+ x 1))"))
    ], "definition");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(define f 4)"), /* [] */0, "rackette - definition");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(define f 4)\n         (define g 6)\n         (+ f g)"), {
      hd: "10",
      tl: /* [] */0
    }, "rackette - definitionz and builtin");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(lambda (f) (+ f 4))"), {
      hd: "#<procedure>",
      tl: /* [] */0
    }, "rackette - lambda");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(define f (lambda (x) (+ x 4)))"), /* [] */0, "racette - defing something as lambda");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(define f (lambda (x) (+ x 4)))\n        (f (+ (f 5) 2))"), {
      hd: "15",
      tl: /* [] */0
    }, "racette - user defined function");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(cons 2 (cons 3 (cons 4 empty)))"), {
      hd: "[2,3,4]",
      tl: /* [] */0
    }, "rackette - constructing a list");

CS17SetupRackette$Rackette.checkExpect(Rackette$Rackette.rackette("(define k-subsets-sum (lambda (weights k target)\n  (cond\n    ((and (= k 0) (= target 0)) true)\n    ((and (= k 0) (not (= target 0))) false)\n    ((and (empty? weights) (or (not (= target 0)) (not (= k 0)))) false)\n    ((and (cons? weights) (not (= k 0)))\n     (or (k-subsets-sum (rest weights) (- k 1) (- target (first weights)))\n         (k-subsets-sum (rest weights) k target))))))\n    (k-subsets-sum (cons 1 (cons 2 (cons 3 (cons 4 empty)))) 3 9)\n    (k-subsets-sum empty 0 1)\n    (k-subsets-sum (cons 1 (cons 2 (cons 3 empty))) 2 6)"), {
      hd: "#t",
      tl: {
        hd: "#f",
        tl: {
          hd: "#f",
          tl: /* [] */0
        }
      }
    }, "rackette - k-subsets-sum");

CS17SetupRackette$Rackette.checkError((function (param) {
        return Rackette$Rackette.rackette("(cons 3)");
      }), "too few arguments for cons");

CS17SetupRackette$Rackette.checkError((function (param) {
        return Rackette$Rackette.rackette("(+ 1)");
      }), "too few arguments for add");

CS17SetupRackette$Rackette.checkError((function (param) {
        return Rackette$Rackette.rackette("(cond true 4)");
      }), "Invalid cond clause format");

/*  Not a pure module */
