// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Read$Rackette = require("./Read.bs.js");
var CS17SetupRackette$Rackette = require("./CS17SetupRackette.bs.js");

function add(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for add");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in add");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for add");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in add");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for add");
    } else {
      return Pervasives.failwith("non-number arguments in add");
    }
  } else {
    return {
            TAG: /* NumV */0,
            _0: _hd._0 + tl._0 | 0
          };
  }
}

function subtract(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for subtract");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in subtract");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for subtract");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in subtract");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for subtract");
    } else {
      return Pervasives.failwith("non-number arguments in subtract");
    }
  } else {
    return {
            TAG: /* NumV */0,
            _0: _hd._0 - tl._0 | 0
          };
  }
}

function multiply(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for multiply");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in multiply");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for multiply");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in multiply");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for multiply");
    } else {
      return Pervasives.failwith("non-number arguments in multiply");
    }
  } else {
    return {
            TAG: /* NumV */0,
            _0: Math.imul(_hd._0, tl._0)
          };
  }
}

function divide(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for divide");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in divide");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for divide");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in divide");
  }
  var tl$1 = tl._0;
  if (tl$1 === 0 && !match.tl) {
    return Pervasives.failwith("Divide by zero error");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for divide");
    } else {
      return Pervasives.failwith("non-number arguments in divide");
    }
  } else {
    return {
            TAG: /* NumV */0,
            _0: Caml_int32.div(_hd._0, tl$1)
          };
  }
}

function modulo(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for remainder");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in remainder");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for remainder");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in remainder");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for remainder");
    } else {
      return Pervasives.failwith("non-number arguments in remainder");
    }
  } else {
    return {
            TAG: /* NumV */0,
            _0: Caml_int32.mod_(_hd._0, tl._0)
          };
  }
}

function equalityq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for equalityq");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in equalityq");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for equalityq");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in equalityq");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for equalityq");
    } else {
      return Pervasives.failwith("non-number arguments in equalityq");
    }
  } else {
    return {
            TAG: /* BoolV */1,
            _0: _hd._0 === tl._0
          };
  }
}

function lessThanq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for less than");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in less than");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for less than");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in less than");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for less than");
    } else {
      return Pervasives.failwith("non-number arguments in less than");
    }
  } else {
    return {
            TAG: /* BoolV */1,
            _0: _hd._0 < tl._0
          };
  }
}

function greaterThanq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for greater than");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in greater than");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for greater than");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in greater than");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for greater than");
    } else {
      return Pervasives.failwith("non-number arguments in greater than");
    }
  } else {
    return {
            TAG: /* BoolV */1,
            _0: _hd._0 > tl._0
          };
  }
}

function leqq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for <=");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in <=");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for <=");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in <=");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for <=");
    } else {
      return Pervasives.failwith("non-number arguments in <=");
    }
  } else {
    return {
            TAG: /* BoolV */1,
            _0: _hd._0 <= tl._0
          };
  }
}

function geqq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for >=");
  }
  var _hd = alov.hd;
  if (_hd.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in >=");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for >=");
  }
  var tl = match.hd;
  if (tl.TAG !== /* NumV */0) {
    return Pervasives.failwith("non-number arguments in >=");
  }
  var match$1 = match.tl;
  if (match$1) {
    if (match$1.hd.TAG === /* NumV */0) {
      return Pervasives.failwith("too many arguments for >=");
    } else {
      return Pervasives.failwith("non-number arguments in >=");
    }
  } else {
    return {
            TAG: /* BoolV */1,
            _0: _hd._0 >= tl._0
          };
  }
}

function equalq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for equal");
  }
  var _val = alov.hd;
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for equal");
  }
  if (match.tl) {
    return Pervasives.failwith("too many arguments for equal");
  }
  switch (_val.TAG | 0) {
    case /* NumV */0 :
        var tl = alov.tl.hd;
        if (tl.TAG === /* NumV */0) {
          return {
                  TAG: /* BoolV */1,
                  _0: _val._0 === tl._0
                };
        } else {
          return Pervasives.failwith("non-number arguments in equal");
        }
    case /* BoolV */1 :
        var tl$1 = alov.tl.hd;
        if (tl$1.TAG === /* BoolV */1) {
          return {
                  TAG: /* BoolV */1,
                  _0: _val._0 === tl$1._0
                };
        } else {
          return Pervasives.failwith("non-number arguments in equal");
        }
    default:
      return Pervasives.failwith("non-number arguments in equal");
  }
}

function numberq(alov) {
  if (alov) {
    if (alov.hd.TAG === /* NumV */0) {
      if (alov.tl) {
        if (alov.tl) {
          return Pervasives.failwith("too many arguments for number?");
        } else {
          return {
                  TAG: /* BoolV */1,
                  _0: false
                };
        }
      } else {
        return {
                TAG: /* BoolV */1,
                _0: true
              };
      }
    } else if (alov.tl) {
      return Pervasives.failwith("too many arguments for number?");
    } else {
      return {
              TAG: /* BoolV */1,
              _0: false
            };
    }
  } else {
    return Pervasives.failwith("too few arguments for number?");
  }
}

function zeroq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for zero?");
  }
  var hd = alov.hd;
  if (hd.TAG === /* NumV */0 && !alov.tl) {
    return {
            TAG: /* BoolV */1,
            _0: hd._0 === 0
          };
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for zero?");
  } else {
    return Pervasives.failwith("non-number argument for zero?");
  }
}

function cons(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for cons");
  }
  var match = alov.tl;
  if (!match) {
    return Pervasives.failwith("too few arguments for cons");
  }
  var myList = match.hd;
  if (myList.TAG === /* ListV */2 && !match.tl) {
    return {
            TAG: /* ListV */2,
            _0: {
              hd: alov.hd,
              tl: myList._0
            }
          };
  }
  if (match.tl) {
    return Pervasives.failwith("too many arguments for cons");
  } else {
    return Pervasives.failwith("improper arguments for cons");
  }
}

function first(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for first");
  }
  var myList = alov.hd;
  if (myList.TAG === /* ListV */2 && !alov.tl) {
    var myList$1 = myList._0;
    if (myList$1) {
      return myList$1.hd;
    } else {
      return Pervasives.failwith("Called first on empty list");
    }
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for first");
  } else {
    return Pervasives.failwith("non list argument in first");
  }
}

function rest(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for rest");
  }
  var myList = alov.hd;
  if (myList.TAG === /* ListV */2 && !alov.tl) {
    var myList$1 = myList._0;
    if (!myList$1) {
      return Pervasives.failwith("Called rest on empty list");
    }
    var tl = myList$1.tl;
    if (tl) {
      return {
              TAG: /* ListV */2,
              _0: tl
            };
    } else {
      return {
              TAG: /* ListV */2,
              _0: /* [] */0
            };
    }
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for rest");
  } else {
    return Pervasives.failwith("non list argument in rest");
  }
}

function emptyq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for empty?");
  }
  var myList = alov.hd;
  if (myList.TAG === /* ListV */2 && !alov.tl) {
    if (myList._0) {
      return {
              TAG: /* BoolV */1,
              _0: false
            };
    } else {
      return {
              TAG: /* BoolV */1,
              _0: true
            };
    }
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for empty?");
  } else {
    return Pervasives.failwith("non list argument in empty?");
  }
}

function consq(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for cons?");
  }
  var myList = alov.hd;
  if (myList.TAG === /* ListV */2 && !alov.tl) {
    if (myList._0) {
      return {
              TAG: /* BoolV */1,
              _0: true
            };
    } else {
      return {
              TAG: /* BoolV */1,
              _0: false
            };
    }
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for cons?");
  } else {
    return Pervasives.failwith("non list argument in cons?");
  }
}

function not_(alov) {
  if (!alov) {
    return Pervasives.failwith("too few arguments for not");
  }
  var myBool = alov.hd;
  if (myBool.TAG === /* BoolV */1 && !alov.tl) {
    return {
            TAG: /* BoolV */1,
            _0: !myBool._0
          };
  }
  if (alov.tl) {
    return Pervasives.failwith("too many arguments for not");
  } else {
    return Pervasives.failwith("non bool argument in not");
  }
}

var initialTle_0 = {
  hd: [
    /* Name */{
      _0: "+"
    },
    {
      TAG: /* BuiltinV */3,
      _0: {
        printedRep: "builtin+",
        bProc: add
      }
    }
  ],
  tl: {
    hd: [
      /* Name */{
        _0: "-"
      },
      {
        TAG: /* BuiltinV */3,
        _0: {
          printedRep: "builtin-",
          bProc: subtract
        }
      }
    ],
    tl: {
      hd: [
        /* Name */{
          _0: "*"
        },
        {
          TAG: /* BuiltinV */3,
          _0: {
            printedRep: "builtin*",
            bProc: multiply
          }
        }
      ],
      tl: {
        hd: [
          /* Name */{
            _0: "/"
          },
          {
            TAG: /* BuiltinV */3,
            _0: {
              printedRep: "builtin/",
              bProc: divide
            }
          }
        ],
        tl: {
          hd: [
            /* Name */{
              _0: "remainder"
            },
            {
              TAG: /* BuiltinV */3,
              _0: {
                printedRep: "builtinRemainder",
                bProc: modulo
              }
            }
          ],
          tl: {
            hd: [
              /* Name */{
                _0: "="
              },
              {
                TAG: /* BuiltinV */3,
                _0: {
                  printedRep: "builtin=",
                  bProc: equalityq
                }
              }
            ],
            tl: {
              hd: [
                /* Name */{
                  _0: "<"
                },
                {
                  TAG: /* BuiltinV */3,
                  _0: {
                    printedRep: "builtin<",
                    bProc: lessThanq
                  }
                }
              ],
              tl: {
                hd: [
                  /* Name */{
                    _0: ">"
                  },
                  {
                    TAG: /* BuiltinV */3,
                    _0: {
                      printedRep: "builtin>",
                      bProc: greaterThanq
                    }
                  }
                ],
                tl: {
                  hd: [
                    /* Name */{
                      _0: "<="
                    },
                    {
                      TAG: /* BuiltinV */3,
                      _0: {
                        printedRep: "builtin<=",
                        bProc: leqq
                      }
                    }
                  ],
                  tl: {
                    hd: [
                      /* Name */{
                        _0: ">="
                      },
                      {
                        TAG: /* BuiltinV */3,
                        _0: {
                          printedRep: "builtin>=",
                          bProc: geqq
                        }
                      }
                    ],
                    tl: {
                      hd: [
                        /* Name */{
                          _0: "equal?"
                        },
                        {
                          TAG: /* BuiltinV */3,
                          _0: {
                            printedRep: "builtinEqual?",
                            bProc: equalq
                          }
                        }
                      ],
                      tl: {
                        hd: [
                          /* Name */{
                            _0: "number?"
                          },
                          {
                            TAG: /* BuiltinV */3,
                            _0: {
                              printedRep: "builtinNumber?",
                              bProc: numberq
                            }
                          }
                        ],
                        tl: {
                          hd: [
                            /* Name */{
                              _0: "zero?"
                            },
                            {
                              TAG: /* BuiltinV */3,
                              _0: {
                                printedRep: "builtinZero?",
                                bProc: zeroq
                              }
                            }
                          ],
                          tl: {
                            hd: [
                              /* Name */{
                                _0: "cons"
                              },
                              {
                                TAG: /* BuiltinV */3,
                                _0: {
                                  printedRep: "builtinCons",
                                  bProc: cons
                                }
                              }
                            ],
                            tl: {
                              hd: [
                                /* Name */{
                                  _0: "first"
                                },
                                {
                                  TAG: /* BuiltinV */3,
                                  _0: {
                                    printedRep: "builtinFirst",
                                    bProc: first
                                  }
                                }
                              ],
                              tl: {
                                hd: [
                                  /* Name */{
                                    _0: "rest"
                                  },
                                  {
                                    TAG: /* BuiltinV */3,
                                    _0: {
                                      printedRep: "builtinRest",
                                      bProc: rest
                                    }
                                  }
                                ],
                                tl: {
                                  hd: [
                                    /* Name */{
                                      _0: "empty?"
                                    },
                                    {
                                      TAG: /* BuiltinV */3,
                                      _0: {
                                        printedRep: "builtinEmpty?",
                                        bProc: emptyq
                                      }
                                    }
                                  ],
                                  tl: {
                                    hd: [
                                      /* Name */{
                                        _0: "cons?"
                                      },
                                      {
                                        TAG: /* BuiltinV */3,
                                        _0: {
                                          printedRep: "builtinCons?",
                                          bProc: consq
                                        }
                                      }
                                    ],
                                    tl: {
                                      hd: [
                                        /* Name */{
                                          _0: "not"
                                        },
                                        {
                                          TAG: /* BuiltinV */3,
                                          _0: {
                                            printedRep: "builtinNot",
                                            bProc: not_
                                          }
                                        }
                                      ],
                                      tl: /* [] */0
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

var initialTle = {
  hd: initialTle_0,
  tl: /* [] */0
};

function lambdaNamesToName(lambdaNames) {
  return List.map((function (symb) {
                switch (symb.TAG | 0) {
                  case /* SymbolC */1 :
                      return /* Name */{
                              _0: symb._0
                            };
                  case /* NumberC */0 :
                  case /* ListC */2 :
                      throw {
                            RE_EXN_ID: "Match_failure",
                            _1: [
                              "Rackette.re",
                              244,
                              8
                            ],
                            Error: new Error()
                          };
                  
                }
              }), lambdaNames);
}

function lstOfCondsToCondDatas(condDatas) {
  return List.map((function (condEntry) {
                switch (condEntry.TAG | 0) {
                  case /* NumberC */0 :
                  case /* SymbolC */1 :
                      break;
                  case /* ListC */2 :
                      var match = condEntry._0;
                      if (match) {
                        var match$1 = match.tl;
                        if (match$1 && !match$1.tl) {
                          return {
                                  conditionExpr: parseExpression(match.hd),
                                  resultExpr: parseExpression(match$1.hd)
                                };
                        }
                        
                      }
                      break;
                  
                }
                throw {
                      RE_EXN_ID: "Match_failure",
                      _1: [
                        "Rackette.re",
                        254,
                        8
                      ],
                      Error: new Error()
                    };
              }), condDatas);
}

function processLetNames(myLetPairs) {
  return List.map((function (pair) {
                switch (pair.TAG | 0) {
                  case /* NumberC */0 :
                  case /* SymbolC */1 :
                      break;
                  case /* ListC */2 :
                      var match = pair._0;
                      if (match) {
                        var myName = match.hd;
                        switch (myName.TAG | 0) {
                          case /* SymbolC */1 :
                              var match$1 = match.tl;
                              if (match$1 && !match$1.tl) {
                                return {
                                        pairName: /* Name */{
                                          _0: myName._0
                                        },
                                        pairExpr: parseExpression(match$1.hd)
                                      };
                              }
                              break;
                          case /* NumberC */0 :
                          case /* ListC */2 :
                              break;
                          
                        }
                      }
                      break;
                  
                }
                throw {
                      RE_EXN_ID: "Match_failure",
                      _1: [
                        "Rackette.re",
                        266,
                        8
                      ],
                      Error: new Error()
                    };
              }), myLetPairs);
}

function parseExpression(input) {
  switch (input.TAG | 0) {
    case /* NumberC */0 :
        return {
                TAG: /* NumE */0,
                _0: input._0
              };
    case /* SymbolC */1 :
        var someVar = input._0;
        switch (someVar) {
          case "empty" :
              return /* EmptyE */0;
          case "false" :
              return {
                      TAG: /* BoolE */1,
                      _0: false
                    };
          case "true" :
              return {
                      TAG: /* BoolE */1,
                      _0: true
                    };
          default:
            return {
                    TAG: /* NameE */2,
                    _0: /* Name */{
                      _0: someVar
                    }
                  };
        }
    case /* ListC */2 :
        var match = input._0;
        if (!match) {
          return Pervasives.failwith("Syntax error");
        }
        var someFunction = match.hd;
        switch (someFunction.TAG | 0) {
          case /* SymbolC */1 :
              switch (someFunction._0) {
                case "and" :
                    var match$1 = match.tl;
                    if (match$1) {
                      var match$2 = match$1.tl;
                      if (match$2 && !match$2.tl) {
                        return {
                                TAG: /* AndE */3,
                                _0: parseExpression(match$1.hd),
                                _1: parseExpression(match$2.hd)
                              };
                      }
                      
                    }
                    break;
                case "cond" :
                    var match$3 = match.tl;
                    if (match$3) {
                      var condDatas = match$3.hd;
                      switch (condDatas.TAG | 0) {
                        case /* NumberC */0 :
                        case /* SymbolC */1 :
                            break;
                        case /* ListC */2 :
                            if (!match$3.tl) {
                              return {
                                      TAG: /* CondE */6,
                                      _0: lstOfCondsToCondDatas(condDatas._0)
                                    };
                            }
                            break;
                        
                      }
                    }
                    break;
                case "if" :
                    var match$4 = match.tl;
                    if (match$4) {
                      var match$5 = match$4.tl;
                      if (match$5) {
                        var match$6 = match$5.tl;
                        if (match$6 && !match$6.tl) {
                          return {
                                  TAG: /* IfE */5,
                                  _0: {
                                    boolExpr: parseExpression(match$4.hd),
                                    trueExpr: parseExpression(match$5.hd),
                                    falseExpr: parseExpression(match$6.hd)
                                  }
                                };
                        }
                        
                      }
                      
                    }
                    break;
                case "lambda" :
                    var match$7 = match.tl;
                    if (match$7) {
                      var names = match$7.hd;
                      switch (names.TAG | 0) {
                        case /* NumberC */0 :
                        case /* SymbolC */1 :
                            break;
                        case /* ListC */2 :
                            var match$8 = match$7.tl;
                            if (match$8 && !match$8.tl) {
                              return {
                                      TAG: /* LambdaE */7,
                                      _0: {
                                        nameList: lambdaNamesToName(names._0),
                                        lambdaBody: parseExpression(match$8.hd)
                                      }
                                    };
                            }
                            break;
                        
                      }
                    }
                    break;
                case "let" :
                    var match$9 = match.tl;
                    if (match$9) {
                      var myLetPairs = match$9.hd;
                      switch (myLetPairs.TAG | 0) {
                        case /* NumberC */0 :
                        case /* SymbolC */1 :
                            break;
                        case /* ListC */2 :
                            var match$10 = match$9.tl;
                            if (match$10 && !match$10.tl) {
                              return {
                                      TAG: /* LetE */8,
                                      _0: {
                                        letPairs: processLetNames(myLetPairs._0),
                                        letBody: parseExpression(match$10.hd)
                                      }
                                    };
                            }
                            break;
                        
                      }
                    }
                    break;
                case "or" :
                    var match$11 = match.tl;
                    if (match$11) {
                      var match$12 = match$11.tl;
                      if (match$12 && !match$12.tl) {
                        return {
                                TAG: /* OrE */4,
                                _0: parseExpression(match$11.hd),
                                _1: parseExpression(match$12.hd)
                              };
                      }
                      
                    }
                    break;
                default:
                  
              }
              return {
                      TAG: /* ApplicationE */9,
                      _0: List.map(parseExpression, match.tl)
                    };
          case /* NumberC */0 :
          case /* ListC */2 :
              return Pervasives.failwith("Syntax error");
          
        }
        break;
    
  }
}

function parseDefinition(input) {
  switch (input.TAG | 0) {
    case /* NumberC */0 :
    case /* SymbolC */1 :
        break;
    case /* ListC */2 :
        var match = input._0;
        if (match) {
          var match$1 = match.hd;
          switch (match$1.TAG | 0) {
            case /* SymbolC */1 :
                if (match$1._0 === "define") {
                  var match$2 = match.tl;
                  if (match$2) {
                    var myName = match$2.hd;
                    switch (myName.TAG | 0) {
                      case /* SymbolC */1 :
                          var match$3 = match$2.tl;
                          if (match$3 && !match$3.tl) {
                            return [
                                    /* Name */{
                                      _0: myName._0
                                    },
                                    parseExpression(match$3.hd)
                                  ];
                          }
                          break;
                      case /* NumberC */0 :
                      case /* ListC */2 :
                          break;
                      
                    }
                  }
                  
                }
                break;
            case /* NumberC */0 :
            case /* ListC */2 :
                break;
            
          }
        }
        break;
    
  }
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "Rackette.re",
          313,
          4
        ],
        Error: new Error()
      };
}

function parsePiece(input) {
  switch (input.TAG | 0) {
    case /* NumberC */0 :
    case /* SymbolC */1 :
        return Pervasives.failwith("expressions not yet parsed");
    case /* ListC */2 :
        var match = input._0;
        if (!match) {
          return Pervasives.failwith("expressions not yet parsed");
        }
        var match$1 = match.hd;
        switch (match$1.TAG | 0) {
          case /* SymbolC */1 :
              if (match$1._0 === "define") {
                return Pervasives.failwith("definitions not yet parsed");
              } else {
                return Pervasives.failwith("expressions not yet parsed");
              }
          case /* NumberC */0 :
          case /* ListC */2 :
              return Pervasives.failwith("expressions not yet parsed");
          
        }
    
  }
}

function parse(input) {
  return List.map(parsePiece, input);
}

function $$eval(tle, env, expr) {
  return Pervasives.failwith("eval is not yet implemented");
}

function inBindingList(alob, myName) {
  if (alob) {
    return true;
  } else {
    return false;
  }
}

function inEnviorment(_env, myName) {
  while(true) {
    var env = _env;
    if (env) {
      var bindingList1 = env.hd;
      if (!bindingList1 && !env.tl) {
        return false;
      }
      if (inBindingList(bindingList1, myName)) {
        return true;
      }
      _env = env.tl;
      continue ;
    }
    throw {
          RE_EXN_ID: "Match_failure",
          _1: [
            "Rackette.re",
            354,
            4
          ],
          Error: new Error()
        };
  };
}

function addDefinition(env, param) {
  var id = param[0];
  if (inEnviorment(env, id)) {
    return env;
  }
  if (env) {
    return {
            hd: {
              hd: [
                id,
                List.hd($$process({
                          hd: {
                            TAG: /* Expression */1,
                            _0: param[1]
                          },
                          tl: /* [] */0
                        }))
              ],
              tl: env.hd
            },
            tl: env.tl
          };
  }
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "Rackette.re",
          368,
          11
        ],
        Error: new Error()
      };
}

function $$process(pieces) {
  var processHelper = function (_tle, _pieces) {
    while(true) {
      var pieces = _pieces;
      var tle = _tle;
      if (!pieces) {
        return /* [] */0;
      }
      var d = pieces.hd;
      if (d.TAG !== /* Definition */0) {
        return {
                hd: Pervasives.failwith("eval is not yet implemented"),
                tl: processHelper(tle, pieces.tl)
              };
      }
      var d$1 = d._0;
      _pieces = pieces.tl;
      _tle = addDefinition(tle, [
            d$1[0],
            d$1[1]
          ]);
      continue ;
    };
  };
  return processHelper(initialTle, pieces);
}

function stringOfValue(aValue) {
  return Pervasives.failwith("stringOfValue is not yet implemented");
}

function rackette(program) {
  return List.map(stringOfValue, $$process(List.map(parsePiece, Read$Rackette.Reader.readAll(program))));
}

CS17SetupRackette$Rackette.checkExpectExpression(parseExpression({
          TAG: /* SymbolC */1,
          _0: "empty"
        }), /* EmptyE */0, "parse empty expression");

CS17SetupRackette$Rackette.checkExpectExpression(parseExpression(Read$Rackette.Reader.read("empty")), /* EmptyE */0, "read and parse empty expression");

exports.add = add;
exports.subtract = subtract;
exports.multiply = multiply;
exports.divide = divide;
exports.modulo = modulo;
exports.equalityq = equalityq;
exports.lessThanq = lessThanq;
exports.greaterThanq = greaterThanq;
exports.leqq = leqq;
exports.geqq = geqq;
exports.equalq = equalq;
exports.numberq = numberq;
exports.zeroq = zeroq;
exports.cons = cons;
exports.first = first;
exports.rest = rest;
exports.emptyq = emptyq;
exports.consq = consq;
exports.not_ = not_;
exports.initialTle = initialTle;
exports.lambdaNamesToName = lambdaNamesToName;
exports.lstOfCondsToCondDatas = lstOfCondsToCondDatas;
exports.processLetNames = processLetNames;
exports.parseExpression = parseExpression;
exports.parseDefinition = parseDefinition;
exports.parsePiece = parsePiece;
exports.parse = parse;
exports.$$eval = $$eval;
exports.inBindingList = inBindingList;
exports.inEnviorment = inEnviorment;
exports.addDefinition = addDefinition;
exports.$$process = $$process;
exports.stringOfValue = stringOfValue;
exports.rackette = rackette;
/*  Not a pure module */
